### ISSUE TITLE
The expected format of CartErrorCode doesn't match the described in the documentation

### ISSUE THREAD

**Issue by mrnone** [Microsoft/Partner-Center-Java#10]
# Steps to reproduce

1) Intentionally prepare a new cart that couldn't be created because of an error in a line item.
2) Submit the cart using "IEntityCreateOperations.create" method

## Expected behavior
The method returns an updated cart which line item has "error" field with a defined "error code" field.

## Actual behavior
The method returns an updated cart which line item has "error" field but "error code" field is undefined.

# Additional information
This is happening because "Cart Error Code" is represented as "integer" (see https://docs.microsoft.com/en-us/partner-center/develop/cart#carterrorcode). However, enumeration "CartErrorCode" tries to treat it as "string".

**Comment by isaiahwilliams** [comment]
Hi @mrnone, 

Thank you for creating this issue and the fix. We really appreciate you helping with this. Please let us know if there is anything we can do to help you.
