### ISSUE TITLE
Ontime BillingLineItems Parsing error in SDK 1.15.3

### ISSUE THREAD

**Issue by gagan2730** [microsoft/Partner-Center-Java#116]
getting following error while trying to fetch BillingLine items for provider ONE_TIME from PC SDK Version 1.15.3.

"Could not deserialize response. Detailed message: InvoiceLineItemConverter cannot deserialize invoice line items with type billing_line_items and billing provider: one_time (through reference chain: com.microsoft.store.partnercenter.models.ResourceCollection[\"items\"]->java.util.ArrayList[0])"

**Comment by gagan2730** [comment]
Thankyou for resolution. Now there is no Parsing Issue in Billing Line Items. However SDK is not able to fetch USAGELINEITEMS for provider ONE_TIME. It returns a blank array as response. we tried fetching the usage details for the Invoice#: G000575783 and G000781864 using the Partner Center API (get-invoice-billed-consumption-lineitems) and we were able to get the details in the API Response, but the same was not working when using Partner Center Java SDK.

**Comment by msize** [comment]
@gagan2730 There you mean that this change brokes USAGELINEITEMS for provider ONE_TIME?

**Comment by gagan2730** [comment]
No @msize , patch didnt broke it. it wasn't working from beginning when i setup a fresh 1.15.3 SDK.

**Comment by msize** [comment]
@gagan2730 The good way it to create another issue for this case.
