### ISSUE TITLE
Bug in Conversion class ,BillingCycleType in SDK  but BillingCycle in API ,

### ISSUE THREAD

**Issue by iovex** [microsoft/Partner-Center-Java#54]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, sample project, version of Java etc.

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by isaiahwilliams** [comment]
Hi @iovex, thank you for opening this issue. I just merged the required code changes to address the issue. If you are using the package we publish, these changes will be available when version 1.13.3 is released.

**Comment by isaiahwilliams** [comment]
Hi @iovex, 

Version 1.13.3 has been released. After updating please let us know if you are still having issues.
