### ISSUE TITLE
Unable to get a list of customers

### ISSUE THREAD

**Issue by shubh2600** [microsoft/Partner-Center-Java#56]
# Steps to reproduce
 public void fetchAll() {

        try {

            IAggregatePartner partner = PartnerService.getInstance().createPartnerOperations(genrateAdToken());
            SeekBasedResourceCollection<Customer> customersPage = partner.getCustomers().query(QueryFactory.getInstance().buildIndexedQuery(40));

            IResourceCollectionEnumerator<SeekBasedResourceCollection<Customer>> customersEnumerator =
                    partner.getEnumerators().getCustomers().create(customersPage);

            while (customersEnumerator.hasValue()) {

                Iterable<Customer> customersItems = customersEnumerator.getCurrent().getItems();
                if (customersItems != null) {
                    Iterator<Customer> itr = customersItems.iterator();

                    while (itr.hasNext()) {

                        Customer customerDetail = itr.next();

                        String tenantId = customerDetail.getCompanyProfile().getTenantId();
                        System.out.println(tenantId);
                    }
                }

                customersEnumerator.next();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

 public IPartnerCredentials genrateAdToken() {

        return PartnerCredentials.getInstance().generateByApplicationCredentials(appId, key, domain,
                "https://login.microsoftonline.com/", "https://graph.windows.net");

    }

> Please share the setup, sample project, version of Java etc.
JDK 8 , Azure sdk version - 1.13.2
## Expected behavior
List of all customers

## Actual behavior
[pool-1-thread-1] INFO com.microsoft.aad.adal4j.AuthenticationAuthority - [Correlation ID: b0834a34-ea13-447d-bfeb-453bd1d71704] Instance discovery was successful
Exception in thread "main" java.lang.NullPointerException
	at com.microsoft.store.partnercenter.exception.PartnerResponseParseException.toString(PartnerResponseParseException.java:99)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
	at java.lang.Throwable.printStackTrace(Throwable.java:655)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)

**Comment by shubh2600** [comment]
Same code works on SDK version -1.8.0

**Comment by isaiahwilliams** [comment]
Hi @shubh2600, 

I have not been able to reproduce this issue. Would it be possible for you to try it using version 1.13.4 that was just released?

**Comment by isaiahwilliams** [comment]
Please let us know if you are still experiencing issues with the latest release.
