### ISSUE TITLE
Customer actually created delay

### ISSUE THREAD

**Issue by manuelmazzuola** [microsoft/Partner-Center-Java#57]
After a successful customer creation, I have to wait at least 90 seconds to retrieve the same customer otherwise the client returns `A customer with the tenant Id 'UUID' was not found.` in the first 30 seconds, then after trying again it returns `No company was found to be associated with tenant Id: 'UUID'.` and then after 90 seconds, more or less, the customer retrieve is executed successfully.

Is that normal? To me no because if the customer creation returns OK and returns the customer effectively created, the retrieve should work immediately.

**Comment by isaiahwilliams** [comment]
@manuelmazzuola you should be able to query for a customer after it has been created. If you are still encountering this issue, then I would recommend that you open a support ticket through Partner Center. That way the Partner Center API support team can help investigate what is happening.

**Comment by isaiahwilliams** [comment]
If you are having issues with this SDK please let us know.
