### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/Partner-Center-Java#80]
https://github.com/microsoft/Partner-Center-Java/blob/398afcde7f810f1f68a315645dac57ef14dd9cf2/src/main/java/com/microsoft/store/partnercenter/PartnerService.java#L219

The program can potentially fail to release a system resource.

**Comment by isaiahwilliams** [comment]
Hi @QiAnXinCodeSafe thank you for opening this issue. I have just made the necessary code changes to ensure that all buffers and streams are closed correctly. Also, I wanted to mention we will be pushing version 2.0 to Maven Central this week.
