### ISSUE TITLE
NPE on requests timeout

### ISSUE THREAD

**Issue by manuelmazzuola** [microsoft/Partner-Center-Java#95]
When a request timeouts there is no response to parse and a NPE occures at https://github.com/microsoft/Partner-Center-Java/blob/92a2e566592c4c928d625b9aad04fb69dc2a42d9/src/main/java/com/microsoft/store/partnercenter/exception/PartnerResponseParseException.java#L99

```
java.lang.NullPointerException
	at com.microsoft.store.partnercenter.exception.PartnerResponseParseException.toString(PartnerResponseParseException.java:99)
```

**Comment by isaiahwilliams** [comment]
@manuelmazzuola this issue has been resolved in the upcoming 1.15.2 release. Thank you for bringing it to our attention.
