### ISSUE TITLE
BillingProvider offer one_time instead of onetime

### ISSUE THREAD

**Issue by Tony-Chou** [microsoft/Partner-Center-Java#97]
# Steps to reproduce

This issue is found when we are trying to test the API of [Get invoice's unbilled reconciliation line items] and it returns [Default logger ERROR: Partner service failed response:{"message":"The request is invalid."}].
It seems this API only accepts the value: onetime, not one_time.

## Expected behavior

The correct response.

## Diagnostic logs

Default logger ERROR: Partner service failed response:{"message":"The request is invalid."}

**Comment by isaiahwilliams** [comment]
@Tony-Chou thank you for reporting this issue! Currently we are working on the next release, and I have just created a pull request with a hotfix for the issue. The hope is that we can push the next release by the end of this week.
